FROM node:alpine

WORKDIR '/app'

COPY package.json ./
RUN npm cache clean --force && \
    rm -f package-lock.json && \
    rm -rf node_modules && \
    npm install

COPY ./ ./

CMD ["npm", "run", "start"]
